import os
from datetime import datetime, timedelta, date
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
import chromadb
from langgraph.types import Command
from langgraph.graph import StateGraph, END
from typing_extensions import TypedDict
import sqlite3
import streamlit as st
from huggingface_hub import login, InferenceClient
import requests
import traceback 
from IPython.display import Image, display

st.set_page_config(page_title="Holistic Habit Coach", layout="centered")
st.title("🧘 StartWell AI: Daily Wellness Coach")

#loading env variables so they can be accessed directly
load_dotenv()

CHROMA_DB_DIR    = os.getenv("CHROMA_DB_DIR", "./chroma_db")
EMBEDDING_MODEL  = os.getenv("EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./habit_coach.db")
LLM_MODEL_NAME  = os.getenv("LLM_MODEL", "mistralai/Mistral-7B-Instruct-v0.3")
HF_TOKEN        = os.getenv("HF_TOKEN", None)
HF_API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3"
HEADERS = {"Authorization": f"Bearer {HF_TOKEN}"}

LLM_CLIENT = None
if HF_TOKEN:
    try:
        LLM_CLIENT = InferenceClient(
            provider="together", # Use Together AI as the provider
            api_key=HF_TOKEN,
        )
        st.success("Hugging Face InferenceClient initialized with Together AI provider.")
    except Exception as e:
        st.error(f"Error initializing Hugging Face InferenceClient: {e}. Please check your HF_TOKEN and provider settings.")
else:
    st.warning("Hugging Face token (HF_TOKEN) not found in environment variables. LLM queries may not work.")

try:
    if HF_TOKEN:
        pass 
    else:
        st.warning("Hugging Face token not found. LLM queries may fail.")
except Exception as e:
    st.error(f"Failed to log in to Hugging Face Hub: {e}")

def query_huggingface_model(prompt: str, max_tokens=200):
    if LLM_CLIENT is None:
        print("DEBUG: LLM_CLIENT is not initialized. Cannot make API call.")
        return "Error: Hugging Face InferenceClient not configured. Please check HF_TOKEN."

    try:
        completion = LLM_CLIENT.chat.completions.create(
            model=LLM_MODEL_NAME, 
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=max_tokens,
        )
        
        generated_text = completion.choices[0].message.content
        
        if not isinstance(generated_text, str) or not generated_text.strip():
            print(f"DEBUG: LLM returned non-string or empty content: {generated_text}")
            return "No meaningful response generated by the LLM."
        
        print(f"DEBUG: LLM Generated Text (first 50 chars): {generated_text[:50]}...")
        return generated_text.strip()
        
    except Exception as e:
        print(f"DEBUG: LLM InferenceClient error: {e}")
        traceback.print_exc()
        return f"Error: LLM call failed with {type(e).__name__} - {e}. Check terminal for details."

db_path = DATABASE_URL.replace("sqlite:///", "")
os.makedirs(CHROMA_DB_DIR, exist_ok=True) 

chroma_client = chromadb.PersistentClient(
    path=CHROMA_DB_DIR
)

logs_collection = chroma_client.get_or_create_collection(
    name="wellness_logs",
    metadata={"description": "Embeddings of daily wellness logs"}
)

embed_model = SentenceTransformer(EMBEDDING_MODEL)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS daily_metrics (
  date               TEXT PRIMARY KEY,
  sleep_hours        REAL DEFAULT 0.0,
  exercise_hours     REAL DEFAULT 0.0,
  productivity_hours REAL DEFAULT 0.0,
  self_help_hours    REAL DEFAULT 0.0
)
""")
conn.commit()

cursor.execute("""
CREATE TABLE IF NOT EXISTS daily_tasks (
  date TEXT,
  task TEXT,
  done INTEGER DEFAULT 0,
  PRIMARY KEY (date, task)
)
""")
conn.commit()

def intake_agent(state: dict) -> Command:
    logs: dict = state.get("user_logs", {})
    date_str: str = state.get("date")
    if not logs or not date_str:
        raise ValueError("state must include 'user_logs' and 'date'")
    
    sleep = float(logs.get("sleep", 0.0))
    exercise = float(logs.get("exercise", 0.0))
    productivity = float(logs.get("productivity", 0.0))
    self_help = float(logs.get("self_help", 0.0))

    cursor.execute("""
    INSERT INTO daily_metrics (
        date, sleep_hours, exercise_hours, productivity_hours, self_help_hours
    ) VALUES (?, ?, ?, ?, ?)
    ON CONFLICT(date) DO UPDATE SET
        sleep_hours        = excluded.sleep_hours,
        exercise_hours     = excluded.exercise_hours,
        productivity_hours = excluded.productivity_hours,
        self_help_hours    = excluded.self_help_hours
    """, (date_str, sleep, exercise, productivity, self_help))
    conn.commit()

    text = "; ".join(f"{k}: {v}" for k,v in logs.items())

    embedding = embed_model.encode(text).tolist()
    logs_collection.add(
      documents=[text],
      embeddings=[embedding],
      metadatas=[{"type":"daily_log","timestamp":date_str}],
      ids=[date_str]
    )

    command_to_return = Command(update={"user_input": logs.get("notes","")}, goto="GoalAgent")
    print(f"DEBUG: Intake Agent returning: {command_to_return}")
    return command_to_return

def goal_agent(state: dict) -> Command:
    today_dt = datetime.fromisoformat(state["date"])
    week_ago_dt = today_dt - timedelta(days=6)
    
    dates = [(week_ago_dt + timedelta(days=i)).date().isoformat() for i in range(7)]

    stored = logs_collection.get(ids=dates)
    contexts = stored.get("documents", [])

    initial_notes = state.get("user_logs", {}).get("notes", "").strip()
    if contexts:
        context_text = "Previous logs:\n" + "\n".join(f"- {doc}" for doc in contexts if doc)
    elif initial_notes:
        context_text = f"No previous logs. User notes: {initial_notes}"
    else:
        context_text = "No previous logs or notes available. Proceed to set an initial goal."

    cursor.execute(
        """
        SELECT 
          AVG(sleep_hours),
          AVG(exercise_hours),
          AVG(productivity_hours),
          AVG(self_help_hours)
        FROM daily_metrics
        WHERE date BETWEEN ? AND ?
        """, (dates[0], dates[-1]) 
    )
    row = cursor.fetchone()
    
    avg_sleep, avg_exercise, avg_prod, avg_self = 0.0, 0.0, 0.0, 0.0
    if row and any(val is not None for val in row):
        avg_sleep, avg_exercise, avg_prod, avg_self = [val or 0.0 for val in row]

    prompt = f"""
    You are a wellness coach. Here is the context:
    {context_text}

    Their average metrics over the past week (if any):
    • Sleep:        {avg_sleep  :.1f} hrs/day
    • Exercise:     {avg_exercise:.1f} hrs/day
    • Productivity: {avg_prod   :.1f} hrs/day
    • Self‑help:    {avg_self   :.1f} hrs/day

    Based on this (or the initial notes), propose one weekly SMART goal to improve their wellness balance. 
    Return exactly in this format:

    Goal: <one-sentence SMART goal>

    S: <Specific aspect>
    M: <How to measure>
    A: <Why it’s achievable>
    R: <Why it’s relevant>
    T: <Time-bound target>
    """
    output = query_huggingface_model(prompt)

    command_to_return = Command(
        goto="Planner",
        update={"weekly_goal": output}
    )
    print(f"DEBUG: Goal Agent returning: {command_to_return}")
    return command_to_return

def planner_agent(state: dict) -> Command:
    weekly_goal = state.get("weekly_goal")
    print(f"DEBUG: Planner Agent - received weekly_goal: {weekly_goal}")
    start_date  = datetime.fromisoformat(state.get("date"))

    if not weekly_goal or "Error:" in weekly_goal or "No meaningful response" in weekly_goal:
        command_to_return = Command(
            goto="Advisor",
            update={"daily_tasks": {}}
        )
        print(f"DEBUG: Planner Agent (no goal) returning: {command_to_return}")
        return command_to_return

    prompt = f"""
    You are a task planning assistant. Given the following SMART weekly goal:

    {weekly_goal}

    Split this goal into one clear, actionable task for each day of the next 7 days.
    Return as a numbered list, with each line in the format:<Date>: <Task>
    Use ISO date formatYYYY-MM-DD, starting from {start_date.date().isoformat()}.
    Ensure each line starts with a date inYYYY-MM-DD format followed by ':'.
    Example:
    2025-06-18: Meditate for 10 minutes.
    2025-06-19: Go for a 30-minute walk.
    """
    result = query_huggingface_model(prompt)
    print(f"DEBUG: Planner Agent - raw LLM output for tasks: {result}")

    daily_tasks = {}
    if "Error:" in result or "No meaningful response" in result:
        command_to_return = Command(
            goto="Advisor",
            update={"daily_tasks": {}}
        )
        print(f"DEBUG: Planner Agent (LLM error) returning: {command_to_return}")
        return command_to_return

    for line in result.splitlines():
        line = line.strip()
        if line and ':' in line:
            parts = line.split(':', 1)
            date_str = parts[0].strip()
            task = parts[1].strip() if len(parts) > 1 else ""

            try:
                datetime.fromisoformat(date_str) 
                if task:
                    daily_tasks[date_str] = task
            except ValueError:
                continue
            
    if not daily_tasks:
        command_to_return = Command(
            goto="Advisor",
            update={"daily_tasks": {}} # No tasks, no advice from Planner
        )
        print(f"DEBUG: Planner Agent (no tasks parsed) returning: {command_to_return}")
        return command_to_return

    for date_str, task in daily_tasks.items():
        cursor.execute(
            "INSERT OR IGNORE INTO daily_tasks(date, task, done) VALUES (?, ?, 0)",
            (date_str, task)
        )
    conn.commit()

    command_to_return = Command(
        goto="Advisor",
        update={"daily_tasks": daily_tasks} 
    )
    print(f"DEBUG: Planner Agent returning: {command_to_return}")
    return command_to_return

def advisor_agent(state: dict) -> Command:
    current_advice = str(state.get("weekly_advice", "")).strip() 
    print(f"DEBUG: Advisor Agent - received state (weekly_advice check): '{state.get('weekly_advice')}' (type: {type(state.get('weekly_advice'))})")
    print(f"DEBUG: Advisor Agent - current_advice after .get and str(): '{current_advice}' (type: {type(current_advice)})")

    end_date = datetime.fromisoformat(state["date"]).date()
    start_date = end_date - timedelta(days=6)
    dates = [(start_date + timedelta(days=i)).isoformat() for i in range(7)]

    task_entries = []
    cursor.execute(
        f"SELECT date, task, done FROM daily_tasks WHERE date BETWEEN ? AND ? ORDER BY date",
        (dates[0], dates[-1])
    )
    rows = cursor.fetchall()

    final_advice = ""

    if rows: 
        for d, task, done in rows:
            status = "done" if done else "not done"
            task_entries.append(f"{d}: {task} - {status}")
        tasks_summary = "\n".join(task_entries)

        stored = logs_collection.get(ids=dates)
        log_docs = stored.get("documents", [])
        logs_text = "\n".join(f"- {doc}" for doc in log_docs if doc)
        context_text = logs_text or "No detailed logs available for the past week."

        prompt = f"""
        You are a supportive wellness coach. Here are the details for the past week:

        Daily Logs:
        {context_text}

        Task Completion:
        {tasks_summary}

        Please provide:
        1. Praise for what the user did well.
        2. Constructive feedback on missed tasks.
        3. Suggestions to improve adherence next week.
        4. Any motivational encouragement.

        Return a concise paragraph of advice.
        """
        
        generated_advice = query_huggingface_model(prompt)
        print(f"DEBUG: Advisor Agent - raw LLM output for advice: '{generated_advice}' (type: {type(generated_advice)})")
        
        if "Error:" in generated_advice or "No meaningful response" in generated_advice:
            final_advice = f"Advisor could not generate detailed advice: {generated_advice}"
        else:
            final_advice = generated_advice
            
    else: 
        weekly_goal = state.get("weekly_goal", "") # Getting the goal to provide better context
        
        if "Error:" in weekly_goal or "No meaningful response" in weekly_goal:
            final_advice = "No specific weekly goal was set, so no detailed tasks could be planned. Please ensure your input helps generate a clear goal."
        elif not weekly_goal.strip():
            final_advice = "No weekly goal provided, so no tasks could be planned for advice."
        else:
            final_advice = f"A goal was set ({weekly_goal}), but no tasks were generated for the week. Please refine your goal or task planning."

    final_advice = str(final_advice).strip()
    print(f"DEBUG: Advisor Agent - final_advice to return: '{final_advice}' (type: {type(final_advice)})")

    command_to_return = Command(
        goto=END,
        update={"weekly_advice": final_advice}
    )
    print(f"DEBUG: Advisor Agent returning: {command_to_return}")
    return command_to_return

class WellnessState(TypedDict):
    user_input: str
    date: str
    user_logs: dict
    weekly_goal: str 
    daily_tasks: dict
    weekly_advice: str # Still defined as str, LangGraph will enforce this type

graph = StateGraph(WellnessState) \
    .add_node("Intake", intake_agent) \
    .add_node("GoalAgent", goal_agent) \
    .add_node("Planner", planner_agent) \
    .add_node("Advisor", advisor_agent) \
    .add_edge("Intake", "GoalAgent") \
    .add_edge("GoalAgent", "Planner") \
    .add_edge("Planner", "Advisor") \
    .set_entry_point("Intake") \
    .set_finish_point("Advisor")

app = graph.compile()

graph_image = app.get_graph().draw_mermaid_png()
# st.image(graph_image, caption="Langgraph agent workflow")

# Initialize session state variables if they don't exist
if "weekly_goal" not in st.session_state:
    st.session_state.weekly_goal = "" 
if "daily_tasks" not in st.session_state:
    st.session_state.daily_tasks = {}
if "weekly_advice" not in st.session_state:
    st.session_state.weekly_advice = "" 

with st.sidebar.form("log_form"):    
    st.header("Daily Wellness Log")
    sleep = st.slider("Sleep (hrs)", 0.0, 12.0, 8.0, 0.5)
    exercise = st.number_input("Exercise (hrs)", 0.0, 24.0, 1.0, 0.25)
    productivity = st.number_input("Productivity (hrs)", 0.0, 24.0, 2.0, 0.25)
    self_help = st.number_input("Self-help (hrs)", 0.0, 24.0, 1.0, 0.25)
    notes = st.text_area("Notes (goals/reflection)", "")
    submitted = st.form_submit_button("Submit Log & Generate Plan")
    
    if submitted:
        today = date.today().isoformat()
        user_logs = {
            "sleep": sleep,
            "exercise": exercise,
            "productivity": productivity,
            "self_help": self_help,
            "notes": notes
        }
    
        state_input = {"user_logs": user_logs, "date": today, "weekly_advice": ""} 
        
        with st.spinner("Generating your plan and advice..."):
            try:
                result = app.invoke(state_input)
                print(f"DEBUG: app.invoke result (raw): {result}")

                st.session_state.weekly_goal = str(result.get("weekly_goal", "")).strip()
                st.session_state.daily_tasks = result.get("daily_tasks", {}) 
                if not isinstance(st.session_state.daily_tasks, dict):
                    print(f"CRITICAL: daily_tasks from app.invoke is not a dict: {st.session_state.daily_tasks} (type: {type(st.session_state.daily_tasks)})")
                    st.session_state.daily_tasks = {}

                st.session_state.weekly_advice = str(result.get("weekly_advice", "")).strip() 
                
                if not isinstance(st.session_state.weekly_advice, str):
                    print(f"CRITICAL ERROR: st.session_state.weekly_advice is not a string AFTER assignment! Type: {type(st.session_state.weekly_advice)}")
                    st.session_state.weekly_advice = "Internal Error: Advice could not be formatted correctly."
                
                st.success("Log submitted and plan generated!")
            except Exception as e:
                st.error(f"An error occurred during plan generation: {e}")
                st.session_state.weekly_goal = ""
                st.session_state.daily_tasks = {}
                st.session_state.weekly_advice = f"Error: Could not generate plan due to an internal issue. Please check the terminal logs. ({e})"
                print(f"DEBUG: Exception caught in Streamlit UI: {e}")
                traceback.print_exc()

if st.session_state.weekly_goal:
    st.subheader("🎯 Weekly SMART Goal")
    st.write(st.session_state.weekly_goal)
elif submitted: 
    st.info("No weekly goal generated yet. Submit your daily log to get started!")

st.subheader("✅ Today's Tasks")
today = date.today().isoformat()

today_tasks_from_db = {}
cursor.execute("SELECT task, done FROM daily_tasks WHERE date = ?", (today,))
for task, done in cursor.fetchall():
    today_tasks_from_db[task] = bool(done)

if today_tasks_from_db:
    for task, done_status in today_tasks_from_db.items():
        key = f"task_checkbox_{today}_{task}" 
        new_done_status = st.checkbox(task, value=done_status, key=key)
        
        if new_done_status != done_status:
            cursor.execute(
                "INSERT OR REPLACE INTO daily_tasks(date, task, done) VALUES(?, ?, ?)",
                (today, task, int(new_done_status))
            )
            conn.commit()
            st.rerun() 
else:
    st.info("No tasks planned for today. Submit a log to get your first tasks!")

st.subheader("📅 Weekly Calendar")
end_date = date.today()
start_date = end_date - timedelta(days=6)
dates_in_week = [(start_date + timedelta(days=i)).isoformat() for i in range(7)]

cursor.execute(
    f"SELECT date, task, done FROM daily_tasks WHERE date BETWEEN ? AND ? ORDER BY date",
    (dates_in_week[0], dates_in_week[-1])
)
weekly_tasks_from_db = cursor.fetchall()

if weekly_tasks_from_db:
    tasks_by_date = {d: [] for d in dates_in_week} 
    for d, task, done in weekly_tasks_from_db:
        tasks_by_date[d].append({"task": task, "done": bool(done)})
    
    display_data = []
    for d in dates_in_week:
        tasks_for_day = tasks_by_date.get(d, [])
        if tasks_for_day:
            for task_entry in tasks_for_day:
                display_data.append({
                    "Date": d,
                    "Task": task_entry["task"],
                    "Status": "✅ Done" if task_entry["done"] else "❌ Not Done"
                })
        else:
            display_data.append({"Date": d, "Task": "No task planned", "Status": "-"})
    st.dataframe(display_data, hide_index=True)
else:
    st.info("No weekly tasks available. Generate a plan to see your calendar!")

if st.session_state.weekly_advice:
    st.subheader("💡 Weekly Reflection & Advice")
    st.write(st.session_state.weekly_advice)
elif submitted: 
    st.info("No weekly advice generated yet. Complete your tasks and logs for the agent to provide feedback.")