"""Thin wrapper around the Hugging Face InferenceClient."""
import traceback
from huggingface_hub import InferenceClient

from config import settings


class LLMClient:
    ERROR_PREFIX = "Error:"
    EMPTY_RESPONSE = "No meaningful response generated by the LLM."

    def __init__(self):
        self._client: InferenceClient | None = None
        self._model = settings.llm_model_name
        if settings.hf_token:
            try:
                self._client = InferenceClient(provider=settings.llm_provider, api_key=settings.hf_token)
            except Exception as exc:
                print(f"DEBUG: Failed to init InferenceClient: {exc}")
        else:
            print("DEBUG: HF_TOKEN not set; LLM calls will fail.")

    @property
    def is_ready(self) -> bool:
        return self._client is not None

    def generate(self, prompt: str, max_tokens: int = 200) -> str:
        if self._client is None:
            return f"{self.ERROR_PREFIX} Hugging Face InferenceClient not configured. Please check HF_TOKEN."
        try:
            completion = self._client.chat.completions.create(
                model=self._model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=max_tokens,
            )
            text = completion.choices[0].message.content
            if not isinstance(text, str) or not text.strip():
                return self.EMPTY_RESPONSE
            return text.strip()
        except Exception as exc:
            traceback.print_exc()
            return f"{self.ERROR_PREFIX} LLM call failed with {type(exc).__name__} - {exc}."
